CREATE TABLE `tbl_dashboard_mensal` (
  `id_dashboard_mensal` bigint(20) NOT NULL AUTO_INCREMENT,
  `id_system_cliente` int(11) NOT NULL,
  `ano` smallint(6) NOT NULL,
  `mes` tinyint(4) NOT NULL,
  `dt_periodo_inicial` date NOT NULL,
  `dt_periodo_final` date NOT NULL,
  `dt_processamento` datetime NOT NULL DEFAULT current_timestamp(),
  `qt_estoque_produtos_total` int(11) NOT NULL DEFAULT 0,
  `qt_estoque_total` decimal(18,4) NOT NULL DEFAULT 0.0000,
  `vl_total_estoque` decimal(18,2) NOT NULL DEFAULT 0.00,
  `qt_produtos_importados` int(11) NOT NULL DEFAULT 0,
  `qt_estoque_importados` decimal(18,4) NOT NULL DEFAULT 0.0000,
  `vl_estoque_importados` decimal(18,2) NOT NULL DEFAULT 0.00,
  `qt_produtos_nacionais` int(11) NOT NULL DEFAULT 0,
  `qt_estoque_nacionais` decimal(18,4) NOT NULL DEFAULT 0.0000,
  `vl_estoque_nacionais` decimal(18,2) NOT NULL DEFAULT 0.00,
  `qt_vendas` int(11) NOT NULL DEFAULT 0,
  `qt_clientes_atendidos` int(11) NOT NULL DEFAULT 0,
  `qt_total_itens_pedido` decimal(18,4) NOT NULL DEFAULT 0.0000,
  `qt_produtos_vendidos` int(11) NOT NULL DEFAULT 0,
  `qt_dias_venda` int(11) NOT NULL DEFAULT 0,
  `vl_total_vendas` decimal(18,2) NOT NULL DEFAULT 0.00,
  `vl_total_vendas_cabecalho` decimal(18,2) NOT NULL DEFAULT 0.00,
  `vl_total_produtos` decimal(18,2) NOT NULL DEFAULT 0.00,
  `vl_total_servicos` decimal(18,2) NOT NULL DEFAULT 0.00,
  `qt_produtos_itens` decimal(18,4) NOT NULL DEFAULT 0.0000,
  `qt_servicos_itens` decimal(18,4) NOT NULL DEFAULT 0.0000,
  `vl_medio_produto` decimal(18,2) NOT NULL DEFAULT 0.00,
  `vl_medio_servico` decimal(18,2) NOT NULL DEFAULT 0.00,
  `pc_produtos` decimal(9,4) NOT NULL DEFAULT 0.0000,
  `pc_servicos` decimal(9,4) NOT NULL DEFAULT 0.0000,
  `qt_itens_por_pedido` decimal(18,4) NOT NULL DEFAULT 0.0000,
  `vl_ticket_medio` decimal(18,2) NOT NULL DEFAULT 0.00,
  `vl_ticket_medio_produtos` decimal(18,2) NOT NULL DEFAULT 0.00,
  `vl_ticket_medio_servicos` decimal(18,2) NOT NULL DEFAULT 0.00,
  `vl_medio_diario` decimal(18,2) NOT NULL DEFAULT 0.00,
  `observacao` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id_dashboard_mensal`),
  UNIQUE KEY `uk_dashboard_mensal_cliente_periodo` (`id_system_cliente`,`ano`,`mes`),
  KEY `ix_dashboard_mensal_periodo` (`ano`,`mes`),
  KEY `ix_dashboard_mensal_cliente_data` (`id_system_cliente`,`dt_periodo_inicial`,`dt_periodo_final`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
