CREATE TABLE `tbl_departamento` (
  `ID_DEPARTAMENTO` int(11) NOT NULL AUTO_INCREMENT,
  `ID_SYSTEM_CLIENTE` int(11) DEFAULT 0,
  `ID_LOJA` int(11) DEFAULT 1,
  `ID_USUARIO` int(11) DEFAULT 1,
  `DEPARTAMENTO` varchar(100) DEFAULT NULL,
  `INATIVO` smallint(6) DEFAULT 0,
  `DT_CADASTRO` datetime DEFAULT NULL,
  `DT_EXPORTE` date DEFAULT NULL,
  `DT_UPDATE` date DEFAULT NULL,
  PRIMARY KEY (`ID_DEPARTAMENTO`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
