CREATE TABLE `tbl_categoria_rel` (
  `ID_CATEGORIA` int(11) NOT NULL,
  `ID_PRODUTO` int(11) NOT NULL,
  `ID_SYSTEM_CLIENTE` int(11) DEFAULT 0,
  `ID_LOJA` int(11) DEFAULT 1,
  `ID_DEPARTAMENTO` int(11) DEFAULT 1,
  `ID_USUARIO` int(11) DEFAULT 1,
  `DT_CADASTRO` datetime DEFAULT NULL,
  `DT_EXPORTE` date DEFAULT NULL,
  `DT_UPDATE` date DEFAULT NULL,
  PRIMARY KEY (`ID_CATEGORIA`,`ID_PRODUTO`),
  KEY `ID_SYSTEM_CLIENTE` (`ID_SYSTEM_CLIENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
