CREATE TABLE `tbl_system_config` (
  `ID_SYSTEM_CONFIG` int(11) NOT NULL AUTO_INCREMENT,
  `ID_SYSTEM_CLIENTE` int(11) DEFAULT 0,
  `ID_LOJA` int(11) DEFAULT 1,
  `ID_DEPARTAMENTO` int(11) DEFAULT 1,
  `ID_USUARIO` int(11) DEFAULT 1,
  `ID_WEBSITE_START` int(11) DEFAULT NULL,
  `FLAG_ARREDONDAR_PRECO` int(11) DEFAULT 1,
  `QT_MIN_VERSAO` int(11) DEFAULT 0,
  `CREATEDAT` datetime DEFAULT NULL,
  `UPDATEDAT` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_SYSTEM_CONFIG`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
