CREATE TABLE `tbl_product_woo` (
  `product_id` int(11) NOT NULL,
  `post_id` int(11) DEFAULT NULL,
  `product_name` varchar(300) DEFAULT NULL,
  `product_url` varchar(500) DEFAULT NULL,
  `slug` varchar(300) DEFAULT NULL,
  `image_main` varchar(500) DEFAULT NULL,
  `image1` varchar(500) DEFAULT NULL,
  `image2` varchar(500) DEFAULT NULL,
  `image3` varchar(500) DEFAULT NULL,
  `image4` varchar(500) DEFAULT NULL,
  `image5` varchar(500) DEFAULT NULL,
  `carta_venda` longtext DEFAULT NULL,
  `descricao` longtext DEFAULT NULL,
  `createdat` datetime DEFAULT NULL,
  `flag_content` smallint(4) DEFAULT 0,
  `updatedat` datetime DEFAULT NULL,
  `exportdat` datetime DEFAULT NULL,
  `flag_export` smallint(6) DEFAULT 0,
  `srv_image1` varchar(500) DEFAULT NULL,
  `srv_image2` varchar(500) DEFAULT NULL,
  `srv_image3` varchar(500) DEFAULT NULL,
  `srv_image4` varchar(500) DEFAULT NULL,
  `srv_image5` varchar(500) DEFAULT NULL,
  `srv_image_main` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
