CREATE TABLE `tbl_app_config` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_SYSTEM_CLIENTE` int(11) DEFAULT NULL,
  `APP_ID` int(11) DEFAULT NULL,
  `APP_NAME` varchar(100) DEFAULT NULL,
  `CLIENT_NAME` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) DEFAULT 1,
  `SECTION_JSON` text DEFAULT '{}',
  `BRAND_JSON` text DEFAULT '{}',
  `COMPANY_JSON` text DEFAULT '{}',
  `PAYMENT_METHOD_JSON` text DEFAULT '{}',
  `HOME_CATEGORY_JSON` text DEFAULT '{}',
  `HOME_MENU_JSON` text DEFAULT '{}',
  `HOME_HERO` text DEFAULT '{}',
  `CREATEDAT` datetime DEFAULT NULL,
  `UPDATEDAT` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
