CREATE TABLE `tbl_financeiro_cedente` (
  `ID_FINANCEIRO_CEDENTE` int(11) NOT NULL AUTO_INCREMENT,
  `ID_SYSTEM_CLIENTE` int(11) DEFAULT 0,
  `ID_LOJA` int(11) DEFAULT 1,
  `ID_DEPARTAMENTO` int(11) DEFAULT 1,
  `ID_USUARIO` int(11) DEFAULT 1,
  `DATADOCADASTRO` datetime DEFAULT NULL,
  `NOME` varchar(200) DEFAULT NULL,
  `CATEGORIA` varchar(300) DEFAULT NULL,
  `MODELO` varchar(100) DEFAULT NULL,
  `DATA_CONTRATO` date DEFAULT NULL,
  `DATA_TERMINO` date DEFAULT NULL,
  `OBSERVACOES` longtext DEFAULT NULL,
  `ATIVO` smallint(6) DEFAULT 1,
  `DT_EXPORTE` date DEFAULT NULL,
  `DT_UPDATE` date DEFAULT NULL,
  `CNPJ` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_FINANCEIRO_CEDENTE`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
