CREATE TABLE `tbl_log_operation` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `APP_ID` int(11) DEFAULT 0,
  `SYSTEM_CLIENT_ID` int(11) DEFAULT 0,
  `ORGANIZATION_ID` varchar(200) DEFAULT NULL,
  `USER_ID` varchar(200) DEFAULT NULL,
  `USER_NAME` varchar(300) DEFAULT NULL,
  `USER_ROLE` varchar(100) DEFAULT NULL,
  `PERSON_ID` int(11) DEFAULT 0,
  `ID_USUARIO` int(11) DEFAULT 0,
  `ID_MODULE` int(11) DEFAULT 0,
  `ID_CADASTRO` int(11) DEFAULT 0,
  `LOG` varchar(500) DEFAULT NULL,
  `NOTE` text DEFAULT NULL,
  `CREATEDAT` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
