CREATE TABLE `tbl_carrinho_movimento` (
  `ID_MOVIMENTO` int(11) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(100) DEFAULT NULL,
  `ID_SYSTEM` int(11) DEFAULT 0,
  `ID_LOJA` int(11) DEFAULT 1,
  `ID_USUARIO` int(11) DEFAULT 1,
  `TYPE_BUSINESS` int(11) DEFAULT 3,
  `ID_CARRINHO` int(11) DEFAULT 1,
  `ID_PRODUTO` int(11) DEFAULT 1,
  `QT` int(11) DEFAULT 0,
  `SOURCE URL` varchar(500) DEFAULT NULL,
  `INATIVO` smallint(6) DEFAULT 0,
  `CREATEDAT` datetime DEFAULT NULL,
  `UPDATEDAT` datetime DEFAULT NULL,
  `ANOTACOES` longtext DEFAULT NULL,
  PRIMARY KEY (`ID_MOVIMENTO`)
) ENGINE=InnoDB AUTO_INCREMENT=66 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
