CREATE TABLE `tbl_produto_caracteristica` (
  `ID_CARACTERISTICA` int(11) NOT NULL AUTO_INCREMENT,
  `ID_SYSTEM_CLIENTE` int(11) DEFAULT 0,
  `ID_LOJA` int(11) DEFAULT 1,
  `ID_USUARIO` int(11) DEFAULT 1,
  `ID_DEPARTAMENTO` int(11) DEFAULT 1,
  `ID_PRODUTO` int(11) DEFAULT NULL,
  `CARACTERISTICA` varchar(200) DEFAULT NULL,
  `VALOR` varchar(300) DEFAULT NULL,
  `INATIVO` smallint(6) DEFAULT NULL,
  `FLAG_CARAC_IMP` smallint(6) DEFAULT 0,
  `DT_CADASTRO` datetime DEFAULT NULL,
  `ANOTACOES` longtext DEFAULT NULL,
  `DT_EXPORTE` date DEFAULT NULL,
  `DT_UPDATE` date DEFAULT NULL,
  PRIMARY KEY (`ID_CARACTERISTICA`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
