CREATE TABLE `tbl_conta_financeira` (
  `ID_TBL_CONTA_FINANCEIRA` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_SYSTEM_CLIENTE` int(11) NOT NULL,
  `ID_LOJA` int(11) NOT NULL DEFAULT 0,
  `NOME` varchar(100) NOT NULL,
  `TIPO_CONTA` varchar(20) NOT NULL COMMENT 'BANCO ou DINHEIRO_LOCAL',
  `BANCO` varchar(80) DEFAULT NULL,
  `AGENCIA` varchar(30) DEFAULT NULL,
  `CONTA` varchar(40) DEFAULT NULL,
  `SALDO_INICIAL` decimal(15,2) NOT NULL DEFAULT 0.00,
  `DATA_SALDO_INICIAL` date NOT NULL,
  `ATIVO` tinyint(1) NOT NULL DEFAULT 1,
  `DT_CADASTRO` datetime NOT NULL DEFAULT current_timestamp(),
  `DT_UPDATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_TBL_CONTA_FINANCEIRA`),
  KEY `IDX_CONTA_FIN_CLIENTE_LOJA` (`ID_SYSTEM_CLIENTE`,`ID_LOJA`,`ATIVO`),
  KEY `IDX_CONTA_FIN_TIPO` (`ID_SYSTEM_CLIENTE`,`TIPO_CONTA`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
