CREATE TABLE `tbl_boleto_bancario` (
  `ID_BOLETO` int(11) NOT NULL AUTO_INCREMENT,
  `DT_CADASTRO` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_BOLETO`)
) ENGINE=InnoDB AUTO_INCREMENT=8399 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
