CREATE TABLE `tbl_pedido_tipo_frete` (
  `ID_TIPO_FRETE` int(11) NOT NULL,
  `ID_SYSTEM_CLIENTE` int(11) NOT NULL DEFAULT 0,
  `ID_LOJA` int(11) DEFAULT 1,
  `ID_USUARIO` int(11) DEFAULT 1,
  `ID_DEPARTAMENTO` int(11) DEFAULT 1,
  `TIPO_FRETE` varchar(50) DEFAULT NULL,
  `VALOR_PADRAO` decimal(18,2) DEFAULT 0.00,
  `TAXA_PADRAO` decimal(18,2) DEFAULT 0.00,
  `INATIVO` smallint(6) DEFAULT 0,
  `FLAG_WEB_OFF` smallint(6) DEFAULT 0,
  `ANOTACOES` varchar(300) DEFAULT NULL,
  `DATADOCADASTRO` datetime DEFAULT NULL,
  `DT_EXPORTE` date DEFAULT NULL,
  `DT_UPDATE` date DEFAULT NULL,
  PRIMARY KEY (`ID_TIPO_FRETE`,`ID_SYSTEM_CLIENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
