CREATE TABLE `tbl_preposicao` (
  `ID_PREPOSICAO` int(11) NOT NULL AUTO_INCREMENT,
  `ID_SYSTEM_CLIENTE` int(11) DEFAULT 0,
  `ID_LOJA` int(11) DEFAULT 1,
  `ID_USUARIO` int(11) DEFAULT 1,
  `ID_DEPARTAMENTO` int(11) DEFAULT 1,
  `PREPOSICAO` varchar(20) DEFAULT NULL,
  `PRIORIDADE` int(11) DEFAULT NULL,
  `DT_CADASTRO` datetime DEFAULT NULL,
  `DT_EXPORTE` date DEFAULT NULL,
  `DT_UPDATE` date DEFAULT NULL,
  PRIMARY KEY (`ID_PREPOSICAO`)
) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
