CREATE TABLE `tbl_produto_importe` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRODUTO` varchar(300) DEFAULT NULL,
  `VALOR` decimal(18,6) DEFAULT NULL,
  `SLUG` varchar(200) DEFAULT NULL,
  `FLAG_EXPORT` smallint(4) DEFAULT 0,
  `EXPORTEDAT` datetime DEFAULT NULL,
  `CREATEDAT` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=217 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
