CREATE TABLE `tbl_taxonomy_meta` (
  `ID_TAXONOMY` int(11) NOT NULL,
  `META_TITLE` varchar(300) DEFAULT NULL,
  `META_DESCRIPTION` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`ID_TAXONOMY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
