CREATE TABLE `tbl_produto_loja` (
  `ID_PRODUTO_LOJA` int(11) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(100) DEFAULT NULL,
  `ID_USUARIO` int(11) DEFAULT 1,
  `ID_SYSTEM_ORIGEM` int(11) DEFAULT 0,
  `ID_SYSTEM_DESTINO` int(11) DEFAULT 0,
  `ID_PRODUTO` int(11) DEFAULT NULL,
  `LOJA_ORIGEM` varchar(100) DEFAULT NULL,
  `LOJA_DESTINO` varchar(100) DEFAULT NULL,
  `CREATEDAT` datetime DEFAULT NULL,
  `UPDATEDAT` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_PRODUTO_LOJA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
