CREATE TABLE `tbl_pessoa_categoria` (
  `ID_TBL_PESSOA_CATEGORIA` int(11) NOT NULL AUTO_INCREMENT,
  `ID_SYSTEM_CLIENTE` int(11) DEFAULT 0,
  `ID_LOJA` int(11) DEFAULT 1,
  `ID_DEPARTAMENTO` int(11) DEFAULT 1,
  `ID_USUARIO` int(11) DEFAULT NULL,
  `CATEGORIA` varchar(200) DEFAULT NULL,
  `INATIVO` int(11) DEFAULT 0,
  `DESCRICAO_CATEGORIA` varchar(50) NOT NULL,
  `DATADOCADASTRO` datetime DEFAULT NULL,
  `DT_EXPORTE` date DEFAULT NULL,
  `DT_UPDATE` date DEFAULT NULL,
  PRIMARY KEY (`ID_TBL_PESSOA_CATEGORIA`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
