CREATE TABLE `tbl_keyvalor_categoria` (
  `ID_CATEGORIA` int(11) NOT NULL AUTO_INCREMENT,
  `ID_SYSTEM_CLIENTE` int(11) DEFAULT 0,
  `ID_LOJA` int(11) DEFAULT 1,
  `ID_USUARIO` int(11) DEFAULT 1,
  `ID_DEPARTAMENTO` int(11) DEFAULT 1,
  `ID_ORDER` int(11) DEFAULT 1,
  `ID_PARENT` int(11) DEFAULT 0,
  `ID_TIPO` int(11) DEFAULT 1,
  `ID_MODULO` int(11) DEFAULT 0,
  `CATEGORIA` varchar(500) DEFAULT NULL,
  `NOTAS` longtext DEFAULT NULL,
  `INATIVO` int(11) DEFAULT 0,
  `DT_CADASTRO` datetime DEFAULT NULL,
  `DT_EXPORTE` date DEFAULT NULL,
  `DT_UPDATE` date DEFAULT NULL,
  PRIMARY KEY (`ID_CATEGORIA`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
