CREATE TABLE `tbl_modulo` (
  `ID_TBL_MODULO` int(11) NOT NULL AUTO_INCREMENT,
  `ID_SYSTEM_CLIENTE` int(11) DEFAULT 0,
  `ID_LOJA` int(11) DEFAULT 1,
  `ID_USUARIO` int(11) DEFAULT 1,
  `ID_DEPARTAMENTO` int(11) DEFAULT 1,
  `NOMEDOMODULO` varchar(20) DEFAULT NULL,
  `DT_EXPORTE` date DEFAULT NULL,
  `DT_UPDATE` date DEFAULT NULL,
  PRIMARY KEY (`ID_TBL_MODULO`)
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
