CREATE TABLE `tbl_cupom` (
  `ID_CUPOM` int(11) NOT NULL AUTO_INCREMENT,
  `CUPOM` varchar(100) DEFAULT 'DESC10',
  `TX_DESC` decimal(18,6) DEFAULT NULL,
  `START_DATE` datetime DEFAULT NULL,
  `END_DATE` datetime DEFAULT NULL,
  `DT_CREATED` datetime DEFAULT NULL,
  `DT_UPDATED` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_CUPOM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
