CREATE TABLE `tbl_produto_loja_rel` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(100) DEFAULT NULL,
  `ID_SYSTEM_ORIGEM` int(11) DEFAULT NULL,
  `ID_SYSTEM_DESTINO` int(11) DEFAULT NULL,
  `ID_PRODUTO_ORIGEM` int(11) DEFAULT NULL,
  `ID_PRODUTO_DESTINO` int(11) DEFAULT NULL,
  `CREATEDAT` datetime DEFAULT NULL,
  `UPDATEDAT` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
